name: smart_expense_categorizer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  http: ^1.1.0
  cupertino_icons: ^1.0.8
  firebase_core: ^4.7.0
  cloud_firestore: ^6.3.0
  fl_chart: ^1.1.0
  vector_math: ^2.3.0  # මෙතන 2.3.0 තිබීම අනිවාර්යයි

# මෙන්න මෙතනයි වැරදිලා තිබුණේ. මේක තියෙන්න ඕනේ මේ විදිහටයි:
dependency_overrides:
  vector_math: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/data.csv