// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8wN80UBU9WKrJcWiw2B8Ecd7TuDf6MC8',
    appId: '1:298155782535:web:8690f749911c837b23a322',
    messagingSenderId: '298155782535',
    projectId: 'smart-expense-app-17',
    authDomain: 'smart-expense-app-17.firebaseapp.com',
    storageBucket: 'smart-expense-app-17.firebasestorage.app',
    measurementId: 'G-RQ1KJHPFRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ex6LJUwb5i1SK7nVxVpoxHwDS5wH89Y',
    appId: '1:298155782535:android:4f18eca1a4c3513723a322',
    messagingSenderId: '298155782535',
    projectId: 'smart-expense-app-17',
    storageBucket: 'smart-expense-app-17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcZcNSMjJ2KdG2ceUBSqb8b7YIDH-hdP8',
    appId: '1:298155782535:ios:28a0b99a10f27e1123a322',
    messagingSenderId: '298155782535',
    projectId: 'smart-expense-app-17',
    storageBucket: 'smart-expense-app-17.firebasestorage.app',
    iosBundleId: 'com.example.smartExpenseCategorizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcZcNSMjJ2KdG2ceUBSqb8b7YIDH-hdP8',
    appId: '1:298155782535:ios:28a0b99a10f27e1123a322',
    messagingSenderId: '298155782535',
    projectId: 'smart-expense-app-17',
    storageBucket: 'smart-expense-app-17.firebasestorage.app',
    iosBundleId: 'com.example.smartExpenseCategorizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8wN80UBU9WKrJcWiw2B8Ecd7TuDf6MC8',
    appId: '1:298155782535:web:4dc15048153f4ec523a322',
    messagingSenderId: '298155782535',
    projectId: 'smart-expense-app-17',
    authDomain: 'smart-expense-app-17.firebaseapp.com',
    storageBucket: 'smart-expense-app-17.firebasestorage.app',
    measurementId: 'G-LX5Y72K23E',
  );
}
